os: Visual Studio 2017

artifacts:
  - path: release
    name: rterm-mingw
    type: zip
  - path: release
    name: rterm-msvc
    type: zip

deploy:
    - provider: GitHub
      auth_token:
          secure: sWX4wYH0ZYhsKcO3KuQfsIg46ToY2A7YsRjmumo2PugdMdEtAWxr/yqMQGIOci9S
      artifact: rterm-mingw
      prerelease: true
      on:
          branch: master
          appveyor_repo_tag: true
    - provider: GitHub
      auth_token:
          secure: sWX4wYH0ZYhsKcO3KuQfsIg46ToY2A7YsRjmumo2PugdMdEtAWxr/yqMQGIOci9S
      artifact: rterm-msvc
      prerelease: true
      on:
          branch: master
          appveyor_repo_tag: true

cache:
  - C:\.conan -> conanfile.py
  - C:\Users\appveyor\.conan -> conanfile.py

configuration:
  - mingw
  - msvc

environment:
  matrix:
    - RTERM_LIBS: system
    - RTERM_LIBS: local
    - RTERM_LIBS: conan

install:
  - git submodule update --init --recursive

  - set MINGW=C:\mingw-w64\x86_64-7.2.0-posix-seh-rt_v5-rev1\mingw64
  - set PATH=%PATH:C:\Program Files\Git\usr\bin;=%
  - set PATH=%MINGW%\bin;%MINGW%\lib;%DEPS_PATH%\bin;%PATH%

  - call ci\appveyor\install\%CONFIGURATION%\%RTERM_LIBS%.bat

build_script:
  - call ci\appveyor\compile\%CONFIGURATION%\%RTERM_LIBS%.bat
  - call ci\appveyor\run\run.bat

after_build:
  - call ci\appveyor\release\release.bat
