dist: xenial
sudo: require

language: cpp

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-8

services:
  - xvfb

compiler:
  - gcc
  - clang

env:
  - RTERM_LIBS=system
  - RTERM_LIBS=conan
  - RTERM_LIBS=local

before_install:
  - if [ $CC = gcc ]; then export CC=gcc-8; fi
  - if [ $CXX = g++ ]; then export CXX=g++-8; fi

install:
  # Install dependecies based on installation type
  - ./ci/travis/$RTERM_LIBS.sh

script:
  - ./ci/travis/run.sh
