dist: xenial
sudo: require

language: cpp

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-8

services:
  - xvfb

compiler:
  - gcc
  - clang

env:
  - RTERM_LIBS=local
    BUILD_TYPE=Release
  - RTERM_LIBS=system
    BUILD_TYPE=Release
  - RTERM_LIBS=conan
    BUILD_TYPE=Release

matrix:
  include:
    - compiler: clang
      env:
        RTERM_LIBS=local
        BUILD_TYPE=Sanitizers

before_install:
  - if [ $CC = gcc ]; then export CC=gcc-8; fi
  - if [ $CXX = g++ ]; then export CXX=g++-8; fi

install:
  - ./ci/travis/$RTERM_LIBS.sh

script:
  - ./ci/travis/run.sh
