dist: trusty
sudo: require

language: cpp
compiler: gcc

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-6
      - g++-6
      - cmake3
      - libsdl2-ttf-dev

before_install:
    - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1280x1024x16"

    # install SDL2-2.0.7
    - wget https://libsdl.org/release/SDL2-2.0.7.tar.gz
    - tar xf SDL2-2.0.7.tar.gz
    - cd SDL2-2.0.7
    - mkdir build
    - cd build
    - ../configure
    - make
    - sudo make install
    - cd ../..

before_script:
    - "export DISPLAY=:99.0"
    - "sh -e /etc/init.d/xvfb start"
    - sleep 3 # give xvfb some time to start
    
    - sudo ln -s /usr/bin/gcc-6 /usr/local/bin/gcc
    - sudo ln -s /usr/bin/g++-6 /usr/local/bin/g++

    - export CC=/usr/bin/gcc-6
    - export CXX=/usr/bin/g++-6


script:
    - cmake . && make
    - sudo install liblibterm.so /usr/local/bin/
    - cd ./demo/
    - cmake . && make
    - ./demo --test
