dist: xenial
sudo: require

language: cpp

addons:
    apt:
      sources:
        - ubuntu-toolchain-r-test
      packages:
        - g++-7

compiler:
  - gcc
  - clang

env:
  - RTERM_LIBS=system
  - RTERM_LIBS=conan
  - RTERM_LIBS=local

before_install:
    - if [ $CC = gcc ]; then export CC=gcc-7; fi
    - if [ $CXX = g++ ]; then export CXX=g++-7; fi
    - echo $CXX_FOR_BUILD
    - echo $CXX
    - echo $CC
    - echo $CC_FOR_BUILD

install:
  # Install dependecies based on installation type
  - ./ci/travis/$RTERM_LIBS.sh

before_script:
  # Setup virtual framebuffer for testing
  - ./ci/travis/xvfb.sh

script:
    - echo $RTERM_LIBS
    #    - ci/run.sh
